### ISSUE TITLE
dash in the schema name

### ISSUE THREAD

**Issue by toJanhonen** [josepfrantic/heroku-cleardbdump#4]
dear developer,

first of all - this is an awesome tool!!! i am so thankful you made it!
a minor addition to make it more awesome would be to allow for dash `-` separators in the schema name.

at present, when the local schema name contains a dash `-`, the operation fails with `failing to parse url`

you are the best. thank you for the great work. `<3`

**Comment by josepfrantic** [comment]
Fixed in last version.
